version: '3.8'
services:
  johnny-app:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "4000:4000"
